/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tr.com.metasoft.metaaktar.View;

import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tr.com.metasoft.metaaktar.System.aktarim.InstanceAktarim;
import tr.com.metasoft.metaaktar.System.aktarim.PatientAktarim;
import tr.com.metasoft.metaaktar.System.aktarim.SeriesAktarim;
import tr.com.metasoft.metaaktar.System.aktarim.StudyAktarim;
import tr.com.metasoft.metaaktar.System.database.DatabaseOperations;
import tr.com.metasoft.metaaktar.System.publicEnum;

/**
 *
 * @author Administrator
 */
public class Frame extends javax.swing.JFrame {

    PatientAktarim patientAktarim;
    StudyAktarim studyAktarim;
    SeriesAktarim seriesAktarim;
    InstanceAktarim instanceAktarim;

    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAyar1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfSunucuIp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDbPort = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfDbUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfDbPass = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfBaseFilePath = new javax.swing.JTextField();
        jbAyar1Kaydet = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jtfDbName = new javax.swing.JTextField();
        jpAyar2 = new javax.swing.JPanel();
        jcbPatient = new javax.swing.JCheckBox();
        jcbStudy = new javax.swing.JCheckBox();
        jcbSeri = new javax.swing.JCheckBox();
        jcbInstance = new javax.swing.JCheckBox();
        jbAyar2KaydetVeBaslat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfPatientPagerSize = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtfStudyPagerSize = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtfSeriPagerSize = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtfInstancePagerSize = new javax.swing.JTextField();
        jcbPatientOverwrite = new javax.swing.JCheckBox();
        jcbStudyOverwrite = new javax.swing.JCheckBox();
        jcbSeriOverwrite = new javax.swing.JCheckBox();
        jcbInstanceOverwrite = new javax.swing.JCheckBox();
        jcbDicomAttrsPkUseMax = new javax.swing.JCheckBox();
        jLabel31 = new javax.swing.JLabel();
        jtfDicomAttrsPkStart = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfDicomAttrsMaxPkBeforeStart = new javax.swing.JTextField();
        jlPatientDurum = new javax.swing.JLabel();
        jlStudyDurum = new javax.swing.JLabel();
        jlSeriDurum = new javax.swing.JLabel();
        jlInstanceDurum = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaBaslamadanOncekiUyarilar = new javax.swing.JTextArea();
        jpProgess = new javax.swing.JPanel();
        jbConsole = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jpbPatient = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jlPatientCurrent = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jlPatientTotal = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jpbStudy = new javax.swing.JProgressBar();
        jLabel19 = new javax.swing.JLabel();
        jlStudyCurrent = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jlStudyTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jpbSeri = new javax.swing.JProgressBar();
        jLabel23 = new javax.swing.JLabel();
        jlSeriCurrent = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jlSeriTotal = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jpbInstance = new javax.swing.JProgressBar();
        jLabel27 = new javax.swing.JLabel();
        jlInstanceCurrent = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jlInstanceTotal = new javax.swing.JLabel();
        jbPauseOrCont = new javax.swing.JButton();
        jcbPatientPause = new javax.swing.JCheckBox();
        jcbStudyPause = new javax.swing.JCheckBox();
        jcbSeriPause = new javax.swing.JCheckBox();
        jcbInstancePause = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpAyar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Sunucu IP");

        jtfSunucuIp.setText("192.168.12.132");

        jLabel2.setText("DB Port:");

        jtfDbPort.setText("1433");

        jLabel3.setText("DB User");

        jtfDbUser.setText("sa");

        jLabel4.setText("Pass:");

        jtfDbPass.setText("meta26.soft");

        jLabel5.setText("BaseFilePath");

        jtfBaseFilePath.setText("\\\\192.168.12.132\\MetapacsStorage\\ServerStudies\\");

            jbAyar1Kaydet.setText("Kaydet");
            jbAyar1Kaydet.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbAyar1KaydetActionPerformed(evt);
                }
            });

            jLabel16.setText("Db Name");

            jtfDbName.setText("PACSDB1");

            javax.swing.GroupLayout jpAyar1Layout = new javax.swing.GroupLayout(jpAyar1);
            jpAyar1.setLayout(jpAyar1Layout);
            jpAyar1Layout.setHorizontalGroup(
                jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAyar1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jbAyar1Kaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpAyar1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jtfBaseFilePath)
                        .addGroup(jpAyar1Layout.createSequentialGroup()
                            .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtfSunucuIp)
                                .addGroup(jpAyar1Layout.createSequentialGroup()
                                    .addComponent(jtfDbName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfDbUser)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtfDbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jtfDbPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())))
            );
            jpAyar1Layout.setVerticalGroup(
                jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpAyar1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtfSunucuIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jtfDbPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jtfDbPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfDbName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jpAyar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtfBaseFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jbAyar1Kaydet)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jpAyar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jcbPatient.setText("Patient");

            jcbStudy.setText("Study");

            jcbSeri.setText("Seri");

            jcbInstance.setText("Instance");

            jbAyar2KaydetVeBaslat.setText("Kaydet & Başlat");
            jbAyar2KaydetVeBaslat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbAyar2KaydetVeBaslatActionPerformed(evt);
                }
            });

            jLabel6.setText("Pager Size:");

            jtfPatientPagerSize.setText("100");

            jLabel13.setText("Pager Size:");

            jtfStudyPagerSize.setText("100");

            jLabel14.setText("Pager Size:");

            jtfSeriPagerSize.setText("100");

            jLabel15.setText("Pager Size:");

            jtfInstancePagerSize.setText("50");

            jcbPatientOverwrite.setText("Overwrite");

            jcbStudyOverwrite.setText("Overwrite");

            jcbSeriOverwrite.setText("Overwrite");

            jcbInstanceOverwrite.setText("Overwrite");

            jcbDicomAttrsPkUseMax.setText("MaxPk dan başla");
            jcbDicomAttrsPkUseMax.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jcbDicomAttrsPkUseMaxActionPerformed(evt);
                }
            });

            jLabel31.setText("DicomAttrs Pk Start");

            jLabel7.setText("DicomAttrs MaxPk");

            jtfDicomAttrsMaxPkBeforeStart.setEditable(false);
            jtfDicomAttrsMaxPkBeforeStart.setText("-");

            jlPatientDurum.setText("(0/0)");

            jlStudyDurum.setText("(0/0)");

            jlSeriDurum.setText("(0/0)");

            jlInstanceDurum.setText("(0/0)");

            jtaBaslamadanOncekiUyarilar.setEditable(false);
            jtaBaslamadanOncekiUyarilar.setColumns(20);
            jtaBaslamadanOncekiUyarilar.setRows(5);
            jScrollPane1.setViewportView(jtaBaslamadanOncekiUyarilar);

            javax.swing.GroupLayout jpAyar2Layout = new javax.swing.GroupLayout(jpAyar2);
            jpAyar2.setLayout(jpAyar2Layout);
            jpAyar2Layout.setHorizontalGroup(
                jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpAyar2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpAyar2Layout.createSequentialGroup()
                            .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAyar2Layout.createSequentialGroup()
                                    .addComponent(jtfDicomAttrsPkStart)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jcbDicomAttrsPkUseMax, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jtfDicomAttrsMaxPkBeforeStart)))
                        .addGroup(jpAyar2Layout.createSequentialGroup()
                            .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpAyar2Layout.createSequentialGroup()
                                    .addComponent(jcbStudy)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlStudyDurum))
                                .addGroup(jpAyar2Layout.createSequentialGroup()
                                    .addComponent(jcbPatient)
                                    .addGap(14, 14, 14)
                                    .addComponent(jlPatientDurum))
                                .addGroup(jpAyar2Layout.createSequentialGroup()
                                    .addComponent(jcbSeri)
                                    .addGap(30, 30, 30)
                                    .addComponent(jlSeriDurum))
                                .addGroup(jpAyar2Layout.createSequentialGroup()
                                    .addComponent(jcbInstance)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jlInstanceDurum)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGap(16, 16, 16)
                            .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpAyar2Layout.createSequentialGroup()
                                        .addComponent(jtfStudyPagerSize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbStudyOverwrite))
                                    .addGroup(jpAyar2Layout.createSequentialGroup()
                                        .addComponent(jtfPatientPagerSize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbPatientOverwrite))
                                    .addGroup(jpAyar2Layout.createSequentialGroup()
                                        .addComponent(jtfSeriPagerSize, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcbSeriOverwrite)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAyar2Layout.createSequentialGroup()
                                    .addComponent(jtfInstancePagerSize)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcbInstanceOverwrite)))
                            .addGap(18, 18, 18)
                            .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpAyar2Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jbAyar2KaydetVeBaslat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1)))))
            );
            jpAyar2Layout.setVerticalGroup(
                jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpAyar2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtfDicomAttrsMaxPkBeforeStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(6, 6, 6)
                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcbDicomAttrsPkUseMax)
                        .addComponent(jLabel31)
                        .addComponent(jtfDicomAttrsPkStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpAyar2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbAyar2KaydetVeBaslat))
                        .addGroup(jpAyar2Layout.createSequentialGroup()
                            .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpAyar2Layout.createSequentialGroup()
                                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfPatientPagerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jcbPatientOverwrite))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfStudyPagerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel13)
                                        .addComponent(jcbStudyOverwrite)
                                        .addComponent(jcbStudy)
                                        .addComponent(jlStudyDurum))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jtfSeriPagerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)
                                        .addComponent(jcbSeriOverwrite)
                                        .addComponent(jcbSeri)
                                        .addComponent(jlSeriDurum))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcbInstanceOverwrite)
                                        .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jtfInstancePagerSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(jcbInstance)
                                            .addComponent(jlInstanceDurum))))
                                .addGroup(jpAyar2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbPatient)
                                    .addComponent(jlPatientDurum)))
                            .addContainerGap(22, Short.MAX_VALUE))))
            );

            jpProgess.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jbConsole.setText("Console");

            jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jLabel12.setText("Patient");

            jlPatientCurrent.setText("0");

            jLabel35.setText("/");

            jlPatientTotal.setText("0");

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpbPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlPatientCurrent)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel35)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jlPatientTotal))
            );
            jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPatientCurrent)
                            .addComponent(jLabel35)
                            .addComponent(jlPatientTotal))
                        .addComponent(jLabel12))
                    .addGap(5, 5, 5)
                    .addComponent(jpbPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );

            jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jpbStudy.setMaximum(11000000);

            jLabel19.setText("Study");

            jlStudyCurrent.setText("0");

            jLabel21.setText("/");

            jlStudyTotal.setText("0");

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpbStudy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jLabel19)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlStudyCurrent)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel21)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jlStudyTotal))
            );
            jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jlStudyCurrent)
                        .addComponent(jLabel21)
                        .addComponent(jlStudyTotal))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpbStudy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );

            jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jpbSeri.setMaximum(11000000);

            jLabel23.setText("Seri");

            jlSeriCurrent.setText("0");

            jLabel25.setText("/");

            jlSeriTotal.setText("0");

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpbSeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addComponent(jLabel23)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSeriCurrent)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel25)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jlSeriTotal))
            );
            jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel8Layout.createSequentialGroup()
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel23)
                        .addComponent(jlSeriCurrent)
                        .addComponent(jLabel25)
                        .addComponent(jlSeriTotal))
                    .addGap(5, 5, 5)
                    .addComponent(jpbSeri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );

            jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jpbInstance.setMaximum(11000000);

            jLabel27.setText("Instance");

            jlInstanceCurrent.setText("0");

            jLabel29.setText("/");

            jlInstanceTotal.setText("0");

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpbInstance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jLabel27)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlInstanceCurrent)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel29)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jlInstanceTotal))
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel27)
                        .addComponent(jlInstanceCurrent)
                        .addComponent(jLabel29)
                        .addComponent(jlInstanceTotal))
                    .addGap(5, 5, 5)
                    .addComponent(jpbInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0))
            );

            jbPauseOrCont.setText("Duraklat/Devam Et");
            jbPauseOrCont.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jbPauseOrContActionPerformed(evt);
                }
            });

            jcbPatientPause.setText("Patient");

            jcbStudyPause.setText("Study");

            jcbSeriPause.setText("Seri");

            jcbInstancePause.setText("Instance");

            javax.swing.GroupLayout jpProgessLayout = new javax.swing.GroupLayout(jpProgess);
            jpProgess.setLayout(jpProgessLayout);
            jpProgessLayout.setHorizontalGroup(
                jpProgessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpProgessLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpProgessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpProgessLayout.createSequentialGroup()
                            .addComponent(jcbPatientPause)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbStudyPause)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jcbSeriPause)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jcbInstancePause)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPauseOrCont)
                            .addGap(18, 18, 18)
                            .addComponent(jbConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );
            jpProgessLayout.setVerticalGroup(
                jpProgessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpProgessLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jpProgessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbConsole)
                        .addComponent(jbPauseOrCont)
                        .addComponent(jcbPatientPause)
                        .addComponent(jcbStudyPause)
                        .addComponent(jcbSeriPause)
                        .addComponent(jcbInstancePause))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpAyar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpProgess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpAyar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jpAyar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpAyar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpProgess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jbAyar1KaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAyar1KaydetActionPerformed
        try {
            DatabaseOperations.connect(jtfSunucuIp.getText(), jtfDbPort.getText(), jtfDbName.getText(), jtfDbUser.getText(), jtfDbPass.getText());
            jtfDicomAttrsMaxPkBeforeStart.setText("(" + DatabaseOperations.getDicomAttrsMaxPk() + ")");
            jtfDicomAttrsPkStart.setText(String.valueOf(DatabaseOperations.getDicomAttrsMaxPk() + 1));
            jlPatientDurum.setText(DatabaseOperations.getPatientCount(publicEnum.KayitTipi.AKTARILMIS) + "/" + DatabaseOperations.getPatientCount(publicEnum.KayitTipi.HEPSI) + "(aktarilmis/hepsi)");
            jlStudyDurum.setText(DatabaseOperations.getStudyCount(publicEnum.KayitTipi.AKTARILMIS) + "/" + DatabaseOperations.getStudyCount(publicEnum.KayitTipi.HEPSI) + "(aktarilmis/hepsi)");
            jlSeriDurum.setText(DatabaseOperations.getSeriesCount(publicEnum.KayitTipi.AKTARILMIS) + "/" + DatabaseOperations.getSeriesCount(publicEnum.KayitTipi.HEPSI) + "(aktarilmis/hepsi)");
            jlInstanceDurum.setText(DatabaseOperations.getInstanceCount(publicEnum.KayitTipi.AKTARILMIS) + "/" + DatabaseOperations.getInstanceCount(publicEnum.KayitTipi.HEPSI) + "(aktarilmis/hepsi)");

            //bağlanti basarili olursa editable ı kapa
            for (Component component : jpAyar1.getComponents()) {
                try {
                    component.setEnabled(false);
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }

    }//GEN-LAST:event_jbAyar1KaydetActionPerformed

    private void jbAyar2KaydetVeBaslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAyar2KaydetVeBaslatActionPerformed
        try {
            int availPk = jcbDicomAttrsPkUseMax.isSelected() ? DatabaseOperations.getDicomAttrsMaxPk() + 1 : Integer.valueOf(jtfDicomAttrsPkStart.getText());

            if (jcbPatient.isSelected()) {
                publicEnum.KayitTipi patientKayitTipi = jcbPatientOverwrite.isSelected() ? publicEnum.KayitTipi.HEPSI : publicEnum.KayitTipi.AKTARILMAMIS;
                int patientAktarilacakKayitSayisi = DatabaseOperations.getPatientCount(patientKayitTipi);
                long pagerSize = Long.valueOf(jtfPatientPagerSize.getText());
                patientAktarim = new PatientAktarim(patientKayitTipi, availPk, pagerSize);
                patientAktarim.setProgressObjects(jpbPatient, jlPatientCurrent, jlPatientTotal);

                jtaBaslamadanOncekiUyarilar.append("Patient\n");
                jtaBaslamadanOncekiUyarilar.append("DicomAttrs Pk start:" + availPk + "\n");
                jtaBaslamadanOncekiUyarilar.append("Aktarilacak kayit:" + patientAktarilacakKayitSayisi + "\n");
                availPk = availPk + patientAktarilacakKayitSayisi + 1;
                jtaBaslamadanOncekiUyarilar.append("Bir sonraki kayit icin uygun olan dicomAttrsPk baslangici:" + availPk + "\n");

            }

            if (jcbStudy.isSelected()) {
                publicEnum.KayitTipi studyKayitTipi = jcbStudyOverwrite.isSelected() ? publicEnum.KayitTipi.HEPSI : publicEnum.KayitTipi.AKTARILMAMIS;
                int studyAktarilacakKayitSayisi = DatabaseOperations.getStudyCount(studyKayitTipi);
                long pagerSize = Long.valueOf(jtfStudyPagerSize.getText());
                studyAktarim = new StudyAktarim(studyKayitTipi, availPk, pagerSize);
                studyAktarim.setProgressObjects(jpbStudy, jlStudyCurrent, jlStudyTotal);

                jtaBaslamadanOncekiUyarilar.append("Study" + "\n");
                jtaBaslamadanOncekiUyarilar.append("DicomAttrs Pk start:" + availPk + "\n");
                jtaBaslamadanOncekiUyarilar.append("Aktarilacak kayit:" + studyAktarilacakKayitSayisi + "\n");
                availPk = availPk + studyAktarilacakKayitSayisi + 1;
                jtaBaslamadanOncekiUyarilar.append("Bir sonraki kayit icin uygun olan dicomAttrsPk baslangici:" + availPk + "\n");

            }

            if (jcbSeri.isSelected()) {
                publicEnum.KayitTipi serieKayitTipi = jcbSeriOverwrite.isSelected() ? publicEnum.KayitTipi.HEPSI : publicEnum.KayitTipi.AKTARILMAMIS;
                int serieAktarilacakKayitSayisi = DatabaseOperations.getSeriesCount(serieKayitTipi);
                long pagerSize = Long.valueOf(jtfSeriPagerSize.getText());
                seriesAktarim = new SeriesAktarim(serieKayitTipi, availPk, pagerSize);
                seriesAktarim.setProgressObjects(jpbSeri, jlSeriCurrent, jlSeriTotal);

                jtaBaslamadanOncekiUyarilar.append("Serie" + "\n");
                jtaBaslamadanOncekiUyarilar.append("DicomAttrs Pk start:" + availPk + "\n");
                jtaBaslamadanOncekiUyarilar.append("Aktarilacak kayit:" + serieAktarilacakKayitSayisi + "\n");
                availPk = availPk + serieAktarilacakKayitSayisi + 1;
                jtaBaslamadanOncekiUyarilar.append("Bir sonraki kayit icin uygun olan dicomAttrsPk baslangici:" + availPk + "\n");

            }

            if (jcbInstance.isSelected()) {
                publicEnum.KayitTipi instanceKayitTipi = jcbInstanceOverwrite.isSelected() ? publicEnum.KayitTipi.HEPSI : publicEnum.KayitTipi.AKTARILMAMIS;
                int instanceAktarilacakKayitSayisi = DatabaseOperations.getSeriesCount(instanceKayitTipi);
                long pagerSize = Long.valueOf(jtfInstancePagerSize.getText());
                instanceAktarim = new InstanceAktarim(instanceKayitTipi, availPk, pagerSize, jtfBaseFilePath.getText());
                instanceAktarim.setProgressObjects(jpbInstance, jlInstanceCurrent, jlInstanceTotal);

                jtaBaslamadanOncekiUyarilar.append("Instance" + "\n");
                jtaBaslamadanOncekiUyarilar.append("DicomAttrs Pk start:" + availPk + "\n");
                jtaBaslamadanOncekiUyarilar.append("Aktarilacak kayit:" + instanceAktarilacakKayitSayisi + "\n");
                availPk = availPk + instanceAktarilacakKayitSayisi + 1;
                jtaBaslamadanOncekiUyarilar.append("Bir sonraki kayit icin uygun olan dicomAttrsPk baslangici:" + availPk + "\n");

            }

            if (patientAktarim != null) {
                patientAktarim.aktar();
            }
            if (studyAktarim != null) {
                studyAktarim.aktar();
            }
            if (seriesAktarim != null) {
                seriesAktarim.aktar();
            }
            if (instanceAktarim != null) {
                instanceAktarim.aktar();
            }

            for (Component component : jpAyar2.getComponents()) {
                component.setEnabled(false);
            }
        } catch (Exception ex) {
            Logger.getLogger(Frame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbAyar2KaydetVeBaslatActionPerformed

    private void jcbDicomAttrsPkUseMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbDicomAttrsPkUseMaxActionPerformed
        jtfDicomAttrsPkStart.setEnabled(!jtfDicomAttrsPkStart.isEnabled());
    }//GEN-LAST:event_jcbDicomAttrsPkUseMaxActionPerformed

    private void jbPauseOrContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPauseOrContActionPerformed
//adsh6775 
    }//GEN-LAST:event_jbPauseOrContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAyar1Kaydet;
    private javax.swing.JButton jbAyar2KaydetVeBaslat;
    private javax.swing.JButton jbConsole;
    private javax.swing.JButton jbPauseOrCont;
    private javax.swing.JCheckBox jcbDicomAttrsPkUseMax;
    private javax.swing.JCheckBox jcbInstance;
    private javax.swing.JCheckBox jcbInstanceOverwrite;
    private javax.swing.JCheckBox jcbInstancePause;
    private javax.swing.JCheckBox jcbPatient;
    private javax.swing.JCheckBox jcbPatientOverwrite;
    private javax.swing.JCheckBox jcbPatientPause;
    private javax.swing.JCheckBox jcbSeri;
    private javax.swing.JCheckBox jcbSeriOverwrite;
    private javax.swing.JCheckBox jcbSeriPause;
    private javax.swing.JCheckBox jcbStudy;
    private javax.swing.JCheckBox jcbStudyOverwrite;
    private javax.swing.JCheckBox jcbStudyPause;
    private javax.swing.JLabel jlInstanceCurrent;
    private javax.swing.JLabel jlInstanceDurum;
    private javax.swing.JLabel jlInstanceTotal;
    private javax.swing.JLabel jlPatientCurrent;
    private javax.swing.JLabel jlPatientDurum;
    private javax.swing.JLabel jlPatientTotal;
    private javax.swing.JLabel jlSeriCurrent;
    private javax.swing.JLabel jlSeriDurum;
    private javax.swing.JLabel jlSeriTotal;
    private javax.swing.JLabel jlStudyCurrent;
    private javax.swing.JLabel jlStudyDurum;
    private javax.swing.JLabel jlStudyTotal;
    private javax.swing.JPanel jpAyar1;
    private javax.swing.JPanel jpAyar2;
    private javax.swing.JPanel jpProgess;
    private javax.swing.JProgressBar jpbInstance;
    private javax.swing.JProgressBar jpbPatient;
    private javax.swing.JProgressBar jpbSeri;
    private javax.swing.JProgressBar jpbStudy;
    private javax.swing.JTextArea jtaBaslamadanOncekiUyarilar;
    private javax.swing.JTextField jtfBaseFilePath;
    private javax.swing.JTextField jtfDbName;
    private javax.swing.JTextField jtfDbPass;
    private javax.swing.JTextField jtfDbPort;
    private javax.swing.JTextField jtfDbUser;
    private javax.swing.JTextField jtfDicomAttrsMaxPkBeforeStart;
    private javax.swing.JTextField jtfDicomAttrsPkStart;
    private javax.swing.JTextField jtfInstancePagerSize;
    private javax.swing.JTextField jtfPatientPagerSize;
    private javax.swing.JTextField jtfSeriPagerSize;
    private javax.swing.JTextField jtfStudyPagerSize;
    private javax.swing.JTextField jtfSunucuIp;
    // End of variables declaration//GEN-END:variables
}
